imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig','php'] } #assets_version: SomeVersionScheme
    default_locale:  %locale%
    trust_proxy_headers: false # Whether or not the Request object should trust proxy headers (X_FORWARDED_FOR/HTTP_CLIENT_IP)
    session:         ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: gre
        connections:
            gre:
                driver:   %database_driver%
                host:     %database_host%
                port:     %database_port%
                dbname:   %database_name%
                user:     %database_user%
                password: %database_password%
                charset:  UTF8
            nba:
                driver:   %database_driver%
                host:     %database_host%
                port:     %database_port%
                dbname:   %database_name_nba%
                user:     %database_user%
                password: %database_password%
                charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }
    
    
services:
    db_fetcher:
        class:     James\VocabBundle\DependencyInjection\DbFetcher
        arguments: [@database_connection]
    nba_db_fetcher:
        class:     James\VocabBundle\DependencyInjection\DbFetcher
        arguments: [@doctrine.dbal.nba_connection]
    dictionary:
        class:     James\VocabBundle\DependencyInjection\MWAPIFetcher
        arguments: []
    word_generator:
        class:     James\VocabBundle\DependencyInjection\WordGenerator
        arguments: [@db_fetcher]
    word_manager:
        class:     James\VocabBundle\DependencyInjection\WordManager
        arguments: [@db_fetcher]
    player:
        class:     James\NBAStatsBundle\DependencyInjection\Player
        arguments: [@nba_db_fetcher]
   
    
