parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: jamesjwu_gre
    database_user: jamesjwu
    database_name_nba: jamesjwu_nba
    database_password: Iamthe1king
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 4ac82189ef8b4105f105ad6822efa11a33
    database_path: null
