# src/JamesWu/VocabBundle/Resources/config/services.yml

services:
    db_fetcher:
        class:     James\VocabBundle\DependencyInjection\DbFetcher
        arguments: [@database_connection]
    dictionary:
        class:     James\VocabBundle\DependencyInjection\MWAPIFetcher
        arguments: []
    word_generator:
        class:     James\VocabBundle\DependencyInjection\WordGenerator
        arguments: [@db_fetcher]
    word_manager:
        class:     James\VocabBundle\DependencyInjection\WordManager
        arguments: [@db_fetcher]
